apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5.111.0
          ports:
            - containerPort: 2368
          env:
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "mysql"
            - name: database__connection__user
              value: "ghost"
            - name: database__connection__password
              value: "ghostpassword"
            - name: database__connection__database
              value: "ghostdb"
            - name: url
              value: "https://blog.cloudmasa.com"
          volumeMounts:
            - name: ghost-config
              mountPath: /var/lib/ghost/config.production.json
              subPath: config.production.json
            - name: ghost-storage
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-config
          configMap:
            name: ghost-config
        - name: ghost-storage
          persistentVolumeClaim:
            claimName: ghost-pvc
