apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost-blog
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # AWS Network Load Balancer (NLB)
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  # Public-facing LoadBalancer
    eipalloc-091bcf21fbc4b7c21
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 2368
  selector:
    app: ghost
